### ISSUE TITLE
Running cli_explorer on ATMEL Xplained XMINI -328p

### ISSUE THREAD

**Issue by RandoSY** [piconomix/piconomix-fwlib#10]
Howdy! :)

Seems to be just a little fudge off if the serial port timing if you attempt to run the Arduino cli explorer program on ATMEL's cheap debug board. I toot a look at the F_CPU values, and double uart speed setting and they seem compatible.  I bet it's something simple.

![image](https://github.com/piconomix/px-fwlib/assets/609947/36f674e5-87b4-48df-b082-c64bd268db04)

Thanks!

**Comment by pieterconradie** [comment]
Hi Randy!

See here:
https://github.com/piconomix/px-fwlib/blob/master/boards/avr/atmega328pb_xmini/examples/hello_world/src/main.c#L49-L51

I compensated for the imprecise BAUD rate of mEDBG debugger by specifying a BAUD rate of 111111 instead of 115200.

I hope that helps :)

Kind regards,
Pieter

**Comment by RandoSY** [comment]
That's the ticket, thank you for the consideration of your prompt reply!

![baud correction](https://github.com/piconomix/px-fwlib/assets/609947/4672cf03-1404-4a44-af4a-c78acda212c2)
