### ISSUE TITLE
Non-standard escape sequences used in px_vt100.h

### ISSUE THREAD

**Issue by sbertin-telular** [piconomix/piconomix-fwlib#7]
The VT100 escape sequences all start with "\e", which is a non-standard escape sequence. See https://en.wikipedia.org/wiki/Escape_sequences_in_C#Non-standard_escape_sequences.

I would suggest replacing the "\e" with "\x1B", which is standard and should be supported by all compilers.

**Comment by pieterconradie** [comment]
Hi Scott,

Thanks so much for pointing that out!  Much appreciated :) I have applied your fix and committed it.

Best regards,
Pieter
